version: "3"
services:
  server:
    build: .
    ports:
      - "80:80"
    environment:
      SERVER_PORT: "80"
      DATABASE_CONNECTION_STRING: "jdbc:postgresql://62.113.115.167/test_db"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "admin"
    depends_on:
      - my_db
    networks:
      - my_db_network
    restart: always

  my_db:
    image: "postgres:latest"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "test_db"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "admin"
    volumes:
      - ./db-data:/var/lib/postgresql/data
      - ./sql/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    networks:
      - my_db_network
    restart: always

networks:
  my_db_network:
    driver: bridge